version: 0.2

phases:
  install:
    commands:
      - echo "Install phase started"

  build:
    commands:
      - echo "Creating webpage"
      - mkdir output
      - echo "<html><body><h1>DevOps Experiment 12 Successful</h1></body></html>" > output/index.html

artifacts:
  files:
    - output/index.html
